// Code generated by protoc-gen-easyrpc-ts. DO NOT EDIT.
import { fromBinary, toBinary } from '@bufbuild/protobuf'
import type { Transport, MethodSpec } from 'easy-rpc/protocol'
import { HealthRequest, HealthResponse, EchoRequest, EchoResponse, CountRequest, CountResponse, FailRequest, FailResponse, HealthRequestSchema, HealthResponseSchema, EchoRequestSchema, EchoResponseSchema, CountRequestSchema, CountResponseSchema, FailRequestSchema, FailResponseSchema } from './conformance_pb.js'

export const methodSpecs: MethodSpec[] = [
  { service: "easyrpc.conformance.v1.ConformanceService", name: "Health", path: "/v1/health", httpMethod: "GET", clientStream: false, serverStream: false, body: "" },
  { service: "easyrpc.conformance.v1.ConformanceService", name: "Echo", path: "/v1/echo", httpMethod: "POST", clientStream: false, serverStream: false, body: "*" },
  { service: "easyrpc.conformance.v1.ConformanceService", name: "Count", path: "/v1/count", httpMethod: "POST", clientStream: false, serverStream: true, body: "*" },
  { service: "easyrpc.conformance.v1.ConformanceService", name: "Fail", path: "/v1/fail", httpMethod: "POST", clientStream: false, serverStream: false, body: "*" },
]

export interface ConformanceServiceClient {
  health(req: HealthRequest): Promise<HealthResponse>
  echo(req: EchoRequest): Promise<EchoResponse>
  count(req: CountRequest): Promise<AsyncIterable<CountResponse>>
  fail(req: FailRequest): Promise<FailResponse>
}

export function createConformanceServiceClient(transport: Transport): ConformanceServiceClient {
  return {
    async health(req) {
      const url = "/v1/health"
      const res = await transport.send({ url, method: "GET", headers: { 'content-type': ['application/proto'] }, body: toBinary(HealthRequestSchema, req) })
      if (res.error) throw res.error
      return fromBinary(HealthResponseSchema, res.body)
    },
    async echo(req) {
      const url = "/v1/echo"
      const res = await transport.send({ url, method: "POST", headers: { 'content-type': ['application/proto'] }, body: toBinary(EchoRequestSchema, req) })
      if (res.error) throw res.error
      return fromBinary(EchoResponseSchema, res.body)
    },
    async count(req) {
      const url = "/v1/count"
      const stream = await transport.openStream({ url, method: 'POST', headers: { 'content-type': ['application/connect+proto'] }, body: toBinary(CountRequestSchema, req) })
      return (async function* (): AsyncIterable<CountResponse> {
        for await (const chunk of stream) {
          yield fromBinary(CountResponseSchema, chunk)
        }
      })()
    },
    async fail(req) {
      const url = "/v1/fail"
      const res = await transport.send({ url, method: "POST", headers: { 'content-type': ['application/proto'] }, body: toBinary(FailRequestSchema, req) })
      if (res.error) throw res.error
      return fromBinary(FailResponseSchema, res.body)
    },
  }
}

