// Code generated by protoc-gen-easyrpc-ts. DO NOT EDIT.
import type { MethodSpec } from 'easy-rpc/protocol'

export const methodSpecs: MethodSpec[] = [
  { service: "easyrpc.conformance.v1.ConformanceService", name: "Health", path: "/easyrpc.conformance.v1.ConformanceService/Health", httpMethod: "POST", clientStream: false, serverStream: false, body: "" },
  { service: "easyrpc.conformance.v1.ConformanceService", name: "Echo", path: "/easyrpc.conformance.v1.ConformanceService/Echo", httpMethod: "POST", clientStream: false, serverStream: false, body: "" },
  { service: "easyrpc.conformance.v1.ConformanceService", name: "Count", path: "/easyrpc.conformance.v1.ConformanceService/Count", httpMethod: "POST", clientStream: false, serverStream: true, body: "" },
  { service: "easyrpc.conformance.v1.ConformanceService", name: "Fail", path: "/easyrpc.conformance.v1.ConformanceService/Fail", httpMethod: "POST", clientStream: false, serverStream: false, body: "" },
]

