// @generated by protoc-gen-es v2.14.1 with parameter "target=ts"
// @generated from file easyrpc/conformance/v1/conformance.proto (package easyrpc.conformance.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../../google/api/annotations_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file easyrpc/conformance/v1/conformance.proto.
 */
export const file_easyrpc_conformance_v1_conformance: GenFile = /*@__PURE__*/
  fileDesc("CihlYXN5cnBjL2NvbmZvcm1hbmNlL3YxL2NvbmZvcm1hbmNlLnByb3RvEhZlYXN5cnBjLmNvbmZvcm1hbmNlLnYxIhwKC0VjaG9SZXF1ZXN0Eg0KBWlucHV0GAEgASgJIh4KDEVjaG9SZXNwb25zZRIOCgZvdXRwdXQYASABKAkiHQoMQ291bnRSZXF1ZXN0Eg0KBWNvdW50GAEgASgFIh4KDUNvdW50UmVzcG9uc2USDQoFaW5kZXgYASABKAUiHgoLRmFpbFJlcXVlc3QSDwoHbWVzc2FnZRgBIAEoCSIaCgxGYWlsUmVzcG9uc2USCgoCb2sYASABKAgiDwoNSGVhbHRoUmVxdWVzdCIqCg5IZWFsdGhSZXNwb25zZRIKCgJvaxgBIAEoCBIMCgRuYW1lGAIgASgJMr8DChJDb25mb3JtYW5jZVNlcnZpY2USawoGSGVhbHRoEiUuZWFzeXJwYy5jb25mb3JtYW5jZS52MS5IZWFsdGhSZXF1ZXN0GiYuZWFzeXJwYy5jb25mb3JtYW5jZS52MS5IZWFsdGhSZXNwb25zZSISgtPkkwIMEgovdjEvaGVhbHRoEmYKBEVjaG8SIy5lYXN5cnBjLmNvbmZvcm1hbmNlLnYxLkVjaG9SZXF1ZXN0GiQuZWFzeXJwYy5jb25mb3JtYW5jZS52MS5FY2hvUmVzcG9uc2UiE4LT5JMCDToBKiIIL3YxL2VjaG8SbAoFQ291bnQSJC5lYXN5cnBjLmNvbmZvcm1hbmNlLnYxLkNvdW50UmVxdWVzdBolLmVhc3lycGMuY29uZm9ybWFuY2UudjEuQ291bnRSZXNwb25zZSIUgtPkkwIOOgEqIgkvdjEvY291bnQwARJmCgRGYWlsEiMuZWFzeXJwYy5jb25mb3JtYW5jZS52MS5GYWlsUmVxdWVzdBokLmVhc3lycGMuY29uZm9ybWFuY2UudjEuRmFpbFJlc3BvbnNlIhOC0+STAg06ASoiCC92MS9mYWlsQkBaPmdpdGh1Yi5jb20vZWFzeS11dGlscy9lYXN5LXJwYy1nby9jb25mb3JtYW5jZS92MTtjb25mb3JtYW5jZXYxYgZwcm90bzM", [file_google_api_annotations]);

/**
 * @generated from message easyrpc.conformance.v1.EchoRequest
 */
export type EchoRequest = Message<"easyrpc.conformance.v1.EchoRequest"> & {
  /**
   * @generated from field: string input = 1;
   */
  input: string;
};

/**
 * Describes the message easyrpc.conformance.v1.EchoRequest.
 * Use `create(EchoRequestSchema)` to create a new message.
 */
export const EchoRequestSchema: GenMessage<EchoRequest> = /*@__PURE__*/
  messageDesc(file_easyrpc_conformance_v1_conformance, 0);

/**
 * @generated from message easyrpc.conformance.v1.EchoResponse
 */
export type EchoResponse = Message<"easyrpc.conformance.v1.EchoResponse"> & {
  /**
   * @generated from field: string output = 1;
   */
  output: string;
};

/**
 * Describes the message easyrpc.conformance.v1.EchoResponse.
 * Use `create(EchoResponseSchema)` to create a new message.
 */
export const EchoResponseSchema: GenMessage<EchoResponse> = /*@__PURE__*/
  messageDesc(file_easyrpc_conformance_v1_conformance, 1);

/**
 * @generated from message easyrpc.conformance.v1.CountRequest
 */
export type CountRequest = Message<"easyrpc.conformance.v1.CountRequest"> & {
  /**
   * @generated from field: int32 count = 1;
   */
  count: number;
};

/**
 * Describes the message easyrpc.conformance.v1.CountRequest.
 * Use `create(CountRequestSchema)` to create a new message.
 */
export const CountRequestSchema: GenMessage<CountRequest> = /*@__PURE__*/
  messageDesc(file_easyrpc_conformance_v1_conformance, 2);

/**
 * @generated from message easyrpc.conformance.v1.CountResponse
 */
export type CountResponse = Message<"easyrpc.conformance.v1.CountResponse"> & {
  /**
   * @generated from field: int32 index = 1;
   */
  index: number;
};

/**
 * Describes the message easyrpc.conformance.v1.CountResponse.
 * Use `create(CountResponseSchema)` to create a new message.
 */
export const CountResponseSchema: GenMessage<CountResponse> = /*@__PURE__*/
  messageDesc(file_easyrpc_conformance_v1_conformance, 3);

/**
 * @generated from message easyrpc.conformance.v1.FailRequest
 */
export type FailRequest = Message<"easyrpc.conformance.v1.FailRequest"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;
};

/**
 * Describes the message easyrpc.conformance.v1.FailRequest.
 * Use `create(FailRequestSchema)` to create a new message.
 */
export const FailRequestSchema: GenMessage<FailRequest> = /*@__PURE__*/
  messageDesc(file_easyrpc_conformance_v1_conformance, 4);

/**
 * @generated from message easyrpc.conformance.v1.FailResponse
 */
export type FailResponse = Message<"easyrpc.conformance.v1.FailResponse"> & {
  /**
   * @generated from field: bool ok = 1;
   */
  ok: boolean;
};

/**
 * Describes the message easyrpc.conformance.v1.FailResponse.
 * Use `create(FailResponseSchema)` to create a new message.
 */
export const FailResponseSchema: GenMessage<FailResponse> = /*@__PURE__*/
  messageDesc(file_easyrpc_conformance_v1_conformance, 5);

/**
 * @generated from message easyrpc.conformance.v1.HealthRequest
 */
export type HealthRequest = Message<"easyrpc.conformance.v1.HealthRequest"> & {
};

/**
 * Describes the message easyrpc.conformance.v1.HealthRequest.
 * Use `create(HealthRequestSchema)` to create a new message.
 */
export const HealthRequestSchema: GenMessage<HealthRequest> = /*@__PURE__*/
  messageDesc(file_easyrpc_conformance_v1_conformance, 6);

/**
 * @generated from message easyrpc.conformance.v1.HealthResponse
 */
export type HealthResponse = Message<"easyrpc.conformance.v1.HealthResponse"> & {
  /**
   * @generated from field: bool ok = 1;
   */
  ok: boolean;

  /**
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message easyrpc.conformance.v1.HealthResponse.
 * Use `create(HealthResponseSchema)` to create a new message.
 */
export const HealthResponseSchema: GenMessage<HealthResponse> = /*@__PURE__*/
  messageDesc(file_easyrpc_conformance_v1_conformance, 7);

/**
 * @generated from service easyrpc.conformance.v1.ConformanceService
 */
export const ConformanceService: GenService<{
  /**
   * @generated from rpc easyrpc.conformance.v1.ConformanceService.Health
   */
  health: {
    methodKind: "unary";
    input: typeof HealthRequestSchema;
    output: typeof HealthResponseSchema;
  },
  /**
   * @generated from rpc easyrpc.conformance.v1.ConformanceService.Echo
   */
  echo: {
    methodKind: "unary";
    input: typeof EchoRequestSchema;
    output: typeof EchoResponseSchema;
  },
  /**
   * @generated from rpc easyrpc.conformance.v1.ConformanceService.Count
   */
  count: {
    methodKind: "server_streaming";
    input: typeof CountRequestSchema;
    output: typeof CountResponseSchema;
  },
  /**
   * @generated from rpc easyrpc.conformance.v1.ConformanceService.Fail
   */
  fail: {
    methodKind: "unary";
    input: typeof FailRequestSchema;
    output: typeof FailResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_easyrpc_conformance_v1_conformance, 0);

