// Code generated by protoc-gen-easyrpc-ts. DO NOT EDIT.
import { create, fromBinary, toBinary } from '@bufbuild/protobuf'
import type { MessageInitShape } from '@bufbuild/protobuf'
import type { Transport, MethodSpec, Headers, HandlerContext, ServerStream } from '../../../protocol.js'
import { frame } from '../../../protocol.js'
import type { ServiceHandlers } from '../../../protocol.js'

/** Per-call options: cancellation, extra metadata, and unary trailer hook. */
export interface CallOptions { signal?: AbortSignal; metadata?: Headers; onTrailer?: (trailers: Headers) => void }
import { UnaryRequest, UnaryResponse, ServerStreamRequest, ServerStreamResponse, ClientStreamRequest, ClientStreamResponse, BidiStreamRequest, BidiStreamResponse, UnimplementedRequest, UnimplementedResponse, IdempotentUnaryRequest, IdempotentUnaryResponse, UnaryRequestSchema, UnaryResponseSchema, ServerStreamRequestSchema, ServerStreamResponseSchema, ClientStreamRequestSchema, ClientStreamResponseSchema, BidiStreamRequestSchema, BidiStreamResponseSchema, UnimplementedRequestSchema, UnimplementedResponseSchema, IdempotentUnaryRequestSchema, IdempotentUnaryResponseSchema } from './service_pb.js'

export const methodSpecs: MethodSpec[] = [
  { service: "connectrpc.conformance.v1.ConformanceService", name: "Unary", path: "/connectrpc.conformance.v1.ConformanceService/Unary", clientStream: false, serverStream: false },
  { service: "connectrpc.conformance.v1.ConformanceService", name: "ServerStream", path: "/connectrpc.conformance.v1.ConformanceService/ServerStream", clientStream: false, serverStream: true },
  { service: "connectrpc.conformance.v1.ConformanceService", name: "ClientStream", path: "/connectrpc.conformance.v1.ConformanceService/ClientStream", clientStream: true, serverStream: false },
  { service: "connectrpc.conformance.v1.ConformanceService", name: "BidiStream", path: "/connectrpc.conformance.v1.ConformanceService/BidiStream", clientStream: true, serverStream: true },
  { service: "connectrpc.conformance.v1.ConformanceService", name: "Unimplemented", path: "/connectrpc.conformance.v1.ConformanceService/Unimplemented", clientStream: false, serverStream: false },
  { service: "connectrpc.conformance.v1.ConformanceService", name: "IdempotentUnary", path: "/connectrpc.conformance.v1.ConformanceService/IdempotentUnary", clientStream: false, serverStream: false },
]

export interface ConformanceServiceClient {
  unary(req: MessageInitShape<typeof UnaryRequestSchema>, options?: CallOptions): Promise<UnaryResponse>
  serverStream(req: MessageInitShape<typeof ServerStreamRequestSchema>, options?: CallOptions): Promise<ServerStream<ServerStreamResponse>>
  clientStream(req: MessageInitShape<typeof ClientStreamRequestSchema>, options?: CallOptions): Promise<ClientStreamResponse>
  bidiStream(req: MessageInitShape<typeof BidiStreamRequestSchema>, options?: CallOptions): Promise<ServerStream<BidiStreamResponse>>
  unimplemented(req: MessageInitShape<typeof UnimplementedRequestSchema>, options?: CallOptions): Promise<UnimplementedResponse>
  idempotentUnary(req: MessageInitShape<typeof IdempotentUnaryRequestSchema>, options?: CallOptions): Promise<IdempotentUnaryResponse>
}
export function createConformanceServiceClient(transport: Transport): ConformanceServiceClient {
  return {
    async unary(reqInit, options = {}) {
      const req = create(UnaryRequestSchema, reqInit)
      const ct = 'application/proto'
      const md: Headers = { 'content-type': [ct], accept: [ct], 'connect-protocol-version': ['1'], ...(options.metadata ?? {}) }
      const body = toBinary(UnaryRequestSchema, req)
      const call = { url: "/connectrpc.conformance.v1.ConformanceService/Unary", headers: md, body, ...(options.signal !== undefined ? { signal: options.signal } : {}) }
      const res = await transport.send(call)
      if (res.error) throw res.error
      options.onTrailer?.(res.trailers ?? {})
      return fromBinary(UnaryResponseSchema, res.body)
    },
    async serverStream(reqInit, options = {}) {
      const req = create(ServerStreamRequestSchema, reqInit)
      const ct = 'application/connect+proto'
      const md: Headers = { 'content-type': [ct], accept: [ct], 'connect-protocol-version': ['1'], ...(options.metadata ?? {}) }
      const body = frame(toBinary(ServerStreamRequestSchema, req))
      const call = { url: "/connectrpc.conformance.v1.ConformanceService/ServerStream", headers: md, body, ...(options.signal !== undefined ? { signal: options.signal } : {}) }
      const stream = await transport.openStream(call)
      const out: ServerStream<ServerStreamResponse> = {
        async *[Symbol.asyncIterator]() { for await (const chunk of stream) yield fromBinary(ServerStreamResponseSchema, chunk) },
        trailers: () => stream.trailers(),
        cancel: () => stream.cancel(),
      }
      return out
    },
    async clientStream(reqInit, options = {}) {
      const req = create(ClientStreamRequestSchema, reqInit)
      const ct = 'application/proto'
      const md: Headers = { 'content-type': [ct], accept: [ct], 'connect-protocol-version': ['1'], ...(options.metadata ?? {}) }
      const body = toBinary(ClientStreamRequestSchema, req)
      const call = { url: "/connectrpc.conformance.v1.ConformanceService/ClientStream", headers: md, body, ...(options.signal !== undefined ? { signal: options.signal } : {}) }
      const res = await transport.send(call)
      if (res.error) throw res.error
      options.onTrailer?.(res.trailers ?? {})
      return fromBinary(ClientStreamResponseSchema, res.body)
    },
    async bidiStream(reqInit, options = {}) {
      const req = create(BidiStreamRequestSchema, reqInit)
      const ct = 'application/connect+proto'
      const md: Headers = { 'content-type': [ct], accept: [ct], 'connect-protocol-version': ['1'], ...(options.metadata ?? {}) }
      const body = frame(toBinary(BidiStreamRequestSchema, req))
      const call = { url: "/connectrpc.conformance.v1.ConformanceService/BidiStream", headers: md, body, ...(options.signal !== undefined ? { signal: options.signal } : {}) }
      const stream = await transport.openStream(call)
      const out: ServerStream<BidiStreamResponse> = {
        async *[Symbol.asyncIterator]() { for await (const chunk of stream) yield fromBinary(BidiStreamResponseSchema, chunk) },
        trailers: () => stream.trailers(),
        cancel: () => stream.cancel(),
      }
      return out
    },
    async unimplemented(reqInit, options = {}) {
      const req = create(UnimplementedRequestSchema, reqInit)
      const ct = 'application/proto'
      const md: Headers = { 'content-type': [ct], accept: [ct], 'connect-protocol-version': ['1'], ...(options.metadata ?? {}) }
      const body = toBinary(UnimplementedRequestSchema, req)
      const call = { url: "/connectrpc.conformance.v1.ConformanceService/Unimplemented", headers: md, body, ...(options.signal !== undefined ? { signal: options.signal } : {}) }
      const res = await transport.send(call)
      if (res.error) throw res.error
      options.onTrailer?.(res.trailers ?? {})
      return fromBinary(UnimplementedResponseSchema, res.body)
    },
    async idempotentUnary(reqInit, options = {}) {
      const req = create(IdempotentUnaryRequestSchema, reqInit)
      const ct = 'application/proto'
      const md: Headers = { 'content-type': [ct], accept: [ct], 'connect-protocol-version': ['1'], ...(options.metadata ?? {}) }
      const body = toBinary(IdempotentUnaryRequestSchema, req)
      const call = { url: "/connectrpc.conformance.v1.ConformanceService/IdempotentUnary", headers: md, body, ...(options.signal !== undefined ? { signal: options.signal } : {}) }
      const res = await transport.send(call)
      if (res.error) throw res.error
      options.onTrailer?.(res.trailers ?? {})
      return fromBinary(IdempotentUnaryResponseSchema, res.body)
    },
  }
}

export interface ConformanceServiceServiceImpl {
  unary(req: UnaryRequest, ctx: HandlerContext): Promise<MessageInitShape<typeof UnaryResponseSchema>>
  serverStream(req: ServerStreamRequest, ctx: HandlerContext): AsyncIterable<MessageInitShape<typeof ServerStreamResponseSchema>>
  clientStream(req: ClientStreamRequest, ctx: HandlerContext): Promise<MessageInitShape<typeof ClientStreamResponseSchema>>
  bidiStream(req: BidiStreamRequest, ctx: HandlerContext): AsyncIterable<MessageInitShape<typeof BidiStreamResponseSchema>>
  unimplemented(req: UnimplementedRequest, ctx: HandlerContext): Promise<MessageInitShape<typeof UnimplementedResponseSchema>>
  idempotentUnary(req: IdempotentUnaryRequest, ctx: HandlerContext): Promise<MessageInitShape<typeof IdempotentUnaryResponseSchema>>
}

export function ConformanceServiceHandlers(impl: ConformanceServiceServiceImpl): ServiceHandlers {
  const unary: ServiceHandlers['unary'] = {}
  const stream: ServiceHandlers['stream'] = {}
  unary["Unary"] = async (input, ctx) => {
    const req = fromBinary(UnaryRequestSchema, input)
    const v = create(UnaryResponseSchema, await impl.unary(req, ctx))
    return toBinary(UnaryResponseSchema, v)
  }
  stream["ServerStream"] = async (input, ctx, emit) => {
    const req = fromBinary(ServerStreamRequestSchema, input)
    for await (const v of await impl.serverStream(req, ctx)) { const msg = create(ServerStreamResponseSchema, v); await emit(toBinary(ServerStreamResponseSchema, msg), false) }
    await emit(new Uint8Array(0), true)
  }
  unary["ClientStream"] = async (input, ctx) => {
    const req = fromBinary(ClientStreamRequestSchema, input)
    const v = create(ClientStreamResponseSchema, await impl.clientStream(req, ctx))
    return toBinary(ClientStreamResponseSchema, v)
  }
  stream["BidiStream"] = async (input, ctx, emit) => {
    const req = fromBinary(BidiStreamRequestSchema, input)
    for await (const v of await impl.bidiStream(req, ctx)) { const msg = create(BidiStreamResponseSchema, v); await emit(toBinary(BidiStreamResponseSchema, msg), false) }
    await emit(new Uint8Array(0), true)
  }
  unary["Unimplemented"] = async (input, ctx) => {
    const req = fromBinary(UnimplementedRequestSchema, input)
    const v = create(UnimplementedResponseSchema, await impl.unimplemented(req, ctx))
    return toBinary(UnimplementedResponseSchema, v)
  }
  unary["IdempotentUnary"] = async (input, ctx) => {
    const req = fromBinary(IdempotentUnaryRequestSchema, input)
    const v = create(IdempotentUnaryResponseSchema, await impl.idempotentUnary(req, ctx))
    return toBinary(IdempotentUnaryResponseSchema, v)
  }
  return { unary, stream }
}

