// Code generated by protoc-gen-easyrpc-ts. DO NOT EDIT.
import { create, fromBinary, toBinary, fromJson, toJson, createRegistry } from '@bufbuild/protobuf'
import type { DescMessage } from '@bufbuild/protobuf'
import type { MessageInitShape } from '@bufbuild/protobuf'
import type { Transport, MethodSpec, Headers, HandlerContext, ServerStream } from '../../../protocol.js'
import { frame, contentKindHeader } from '../../../protocol.js'
import type { ContentKind } from '../../../protocol.js'
import type { ServiceHandlers } from '../../../protocol.js'

/** Per-call options: cancellation, extra metadata, and unary trailer hook. */
export interface CallOptions { signal?: AbortSignal; metadata?: Headers; onTrailer?: (trailers: Headers) => void; kind?: ContentKind }
import { file_connectrpc_conformance_v1_service } from './service_pb.js'

/** JSON type registry (required to encode google.protobuf.Any to JSON). */
const jsonRegistry = createRegistry(file_connectrpc_conformance_v1_service)
const toJsonOpts = { registry: jsonRegistry }
import { UnaryRequest, UnaryResponse, ServerStreamRequest, ServerStreamResponse, ClientStreamRequest, ClientStreamResponse, BidiStreamRequest, BidiStreamResponse, UnimplementedRequest, UnimplementedResponse, IdempotentUnaryRequest, IdempotentUnaryResponse, UnaryRequestSchema, UnaryResponseSchema, ServerStreamRequestSchema, ServerStreamResponseSchema, ClientStreamRequestSchema, ClientStreamResponseSchema, BidiStreamRequestSchema, BidiStreamResponseSchema, UnimplementedRequestSchema, UnimplementedResponseSchema, IdempotentUnaryRequestSchema, IdempotentUnaryResponseSchema } from './service_pb.js'

export const methodSpecs: MethodSpec[] = [
  { service: "connectrpc.conformance.v1.ConformanceService", name: "Unary", path: "/connectrpc.conformance.v1.ConformanceService/Unary", clientStream: false, serverStream: false },
  { service: "connectrpc.conformance.v1.ConformanceService", name: "ServerStream", path: "/connectrpc.conformance.v1.ConformanceService/ServerStream", clientStream: false, serverStream: true },
  { service: "connectrpc.conformance.v1.ConformanceService", name: "ClientStream", path: "/connectrpc.conformance.v1.ConformanceService/ClientStream", clientStream: true, serverStream: false },
  { service: "connectrpc.conformance.v1.ConformanceService", name: "BidiStream", path: "/connectrpc.conformance.v1.ConformanceService/BidiStream", clientStream: true, serverStream: true },
  { service: "connectrpc.conformance.v1.ConformanceService", name: "Unimplemented", path: "/connectrpc.conformance.v1.ConformanceService/Unimplemented", clientStream: false, serverStream: false },
  { service: "connectrpc.conformance.v1.ConformanceService", name: "IdempotentUnary", path: "/connectrpc.conformance.v1.ConformanceService/IdempotentUnary", clientStream: false, serverStream: false },
]

export interface ConformanceServiceClient {
  unary(req: MessageInitShape<typeof UnaryRequestSchema>, options?: CallOptions): Promise<UnaryResponse>
  serverStream(req: MessageInitShape<typeof ServerStreamRequestSchema>, options?: CallOptions): Promise<ServerStream<ServerStreamResponse>>
  clientStream(req: MessageInitShape<typeof ClientStreamRequestSchema>, options?: CallOptions): Promise<ClientStreamResponse>
  bidiStream(req: MessageInitShape<typeof BidiStreamRequestSchema>, options?: CallOptions): Promise<ServerStream<BidiStreamResponse>>
  unimplemented(req: MessageInitShape<typeof UnimplementedRequestSchema>, options?: CallOptions): Promise<UnimplementedResponse>
  idempotentUnary(req: MessageInitShape<typeof IdempotentUnaryRequestSchema>, options?: CallOptions): Promise<IdempotentUnaryResponse>
}
export function createConformanceServiceClient(transport: Transport): ConformanceServiceClient {
  return {
    async unary(reqInit, options = {}) {
      const req = create(UnaryRequestSchema, reqInit)
      const kind: ContentKind = options.kind ?? 'proto'
      const ct = contentKindHeader(false, kind)
      const md: Headers = { 'content-type': [ct], accept: [ct], 'connect-protocol-version': ['1'], ...(options.metadata ?? {}) }
      const encode = (): Uint8Array => kind === 'json' ? new TextEncoder().encode(JSON.stringify(toJson(UnaryRequestSchema, req, toJsonOpts))) : toBinary(UnaryRequestSchema, req)
      const body = encode()
      const call = { url: "/connectrpc.conformance.v1.ConformanceService/Unary", headers: md, body, ...(options.signal !== undefined ? { signal: options.signal } : {}) }
      const res = await transport.send(call)
      if (res.error) throw res.error
      options.onTrailer?.(res.trailers ?? {})
      return kind === 'json' ? fromJson(UnaryResponseSchema, JSON.parse(new TextDecoder().decode(res.body))) : fromBinary(UnaryResponseSchema, res.body)
    },
    async serverStream(reqInit, options = {}) {
      const req = create(ServerStreamRequestSchema, reqInit)
      const kind: ContentKind = options.kind ?? 'proto'
      const ct = contentKindHeader(true, kind)
      const md: Headers = { 'content-type': [ct], accept: [ct], 'connect-protocol-version': ['1'], ...(options.metadata ?? {}) }
      const encode = (): Uint8Array => kind === 'json' ? new TextEncoder().encode(JSON.stringify(toJson(ServerStreamRequestSchema, req, toJsonOpts))) : toBinary(ServerStreamRequestSchema, req)
      const body = frame(encode())
      const call = { url: "/connectrpc.conformance.v1.ConformanceService/ServerStream", headers: md, body, ...(options.signal !== undefined ? { signal: options.signal } : {}) }
      const s = await transport.openStream(call)
      const decode = (chunk: Uint8Array) => kind === 'json' ? fromJson(ServerStreamResponseSchema, JSON.parse(new TextDecoder().decode(chunk))) : fromBinary(ServerStreamResponseSchema, chunk)
      const out: ServerStream<ServerStreamResponse> = {
        async *[Symbol.asyncIterator]() { for await (const chunk of s) yield decode(chunk) },
        trailers: () => s.trailers(),
        cancel: () => s.cancel(),
      }
      return out
    },
    async clientStream(reqInit, options = {}) {
      const req = create(ClientStreamRequestSchema, reqInit)
      const kind: ContentKind = options.kind ?? 'proto'
      const ct = contentKindHeader(false, kind)
      const md: Headers = { 'content-type': [ct], accept: [ct], 'connect-protocol-version': ['1'], ...(options.metadata ?? {}) }
      const encode = (): Uint8Array => kind === 'json' ? new TextEncoder().encode(JSON.stringify(toJson(ClientStreamRequestSchema, req, toJsonOpts))) : toBinary(ClientStreamRequestSchema, req)
      const body = encode()
      const call = { url: "/connectrpc.conformance.v1.ConformanceService/ClientStream", headers: md, body, ...(options.signal !== undefined ? { signal: options.signal } : {}) }
      const res = await transport.send(call)
      if (res.error) throw res.error
      options.onTrailer?.(res.trailers ?? {})
      return kind === 'json' ? fromJson(ClientStreamResponseSchema, JSON.parse(new TextDecoder().decode(res.body))) : fromBinary(ClientStreamResponseSchema, res.body)
    },
    async bidiStream(reqInit, options = {}) {
      const req = create(BidiStreamRequestSchema, reqInit)
      const kind: ContentKind = options.kind ?? 'proto'
      const ct = contentKindHeader(true, kind)
      const md: Headers = { 'content-type': [ct], accept: [ct], 'connect-protocol-version': ['1'], ...(options.metadata ?? {}) }
      const encode = (): Uint8Array => kind === 'json' ? new TextEncoder().encode(JSON.stringify(toJson(BidiStreamRequestSchema, req, toJsonOpts))) : toBinary(BidiStreamRequestSchema, req)
      const body = frame(encode())
      const call = { url: "/connectrpc.conformance.v1.ConformanceService/BidiStream", headers: md, body, ...(options.signal !== undefined ? { signal: options.signal } : {}) }
      const s = await transport.openStream(call)
      const decode = (chunk: Uint8Array) => kind === 'json' ? fromJson(BidiStreamResponseSchema, JSON.parse(new TextDecoder().decode(chunk))) : fromBinary(BidiStreamResponseSchema, chunk)
      const out: ServerStream<BidiStreamResponse> = {
        async *[Symbol.asyncIterator]() { for await (const chunk of s) yield decode(chunk) },
        trailers: () => s.trailers(),
        cancel: () => s.cancel(),
      }
      return out
    },
    async unimplemented(reqInit, options = {}) {
      const req = create(UnimplementedRequestSchema, reqInit)
      const kind: ContentKind = options.kind ?? 'proto'
      const ct = contentKindHeader(false, kind)
      const md: Headers = { 'content-type': [ct], accept: [ct], 'connect-protocol-version': ['1'], ...(options.metadata ?? {}) }
      const encode = (): Uint8Array => kind === 'json' ? new TextEncoder().encode(JSON.stringify(toJson(UnimplementedRequestSchema, req, toJsonOpts))) : toBinary(UnimplementedRequestSchema, req)
      const body = encode()
      const call = { url: "/connectrpc.conformance.v1.ConformanceService/Unimplemented", headers: md, body, ...(options.signal !== undefined ? { signal: options.signal } : {}) }
      const res = await transport.send(call)
      if (res.error) throw res.error
      options.onTrailer?.(res.trailers ?? {})
      return kind === 'json' ? fromJson(UnimplementedResponseSchema, JSON.parse(new TextDecoder().decode(res.body))) : fromBinary(UnimplementedResponseSchema, res.body)
    },
    async idempotentUnary(reqInit, options = {}) {
      const req = create(IdempotentUnaryRequestSchema, reqInit)
      const kind: ContentKind = options.kind ?? 'proto'
      const ct = contentKindHeader(false, kind)
      const md: Headers = { 'content-type': [ct], accept: [ct], 'connect-protocol-version': ['1'], ...(options.metadata ?? {}) }
      const encode = (): Uint8Array => kind === 'json' ? new TextEncoder().encode(JSON.stringify(toJson(IdempotentUnaryRequestSchema, req, toJsonOpts))) : toBinary(IdempotentUnaryRequestSchema, req)
      const body = encode()
      const call = { url: "/connectrpc.conformance.v1.ConformanceService/IdempotentUnary", headers: md, body, ...(options.signal !== undefined ? { signal: options.signal } : {}) }
      const res = await transport.send(call)
      if (res.error) throw res.error
      options.onTrailer?.(res.trailers ?? {})
      return kind === 'json' ? fromJson(IdempotentUnaryResponseSchema, JSON.parse(new TextDecoder().decode(res.body))) : fromBinary(IdempotentUnaryResponseSchema, res.body)
    },
  }
}

export interface ConformanceServiceServiceImpl {
  unary(req: UnaryRequest, ctx: HandlerContext): Promise<MessageInitShape<typeof UnaryResponseSchema>>
  serverStream(req: ServerStreamRequest, ctx: HandlerContext): AsyncIterable<MessageInitShape<typeof ServerStreamResponseSchema>>
  clientStream(req: ClientStreamRequest, ctx: HandlerContext): Promise<MessageInitShape<typeof ClientStreamResponseSchema>>
  bidiStream(req: BidiStreamRequest, ctx: HandlerContext): AsyncIterable<MessageInitShape<typeof BidiStreamResponseSchema>>
  unimplemented(req: UnimplementedRequest, ctx: HandlerContext): Promise<MessageInitShape<typeof UnimplementedResponseSchema>>
  idempotentUnary(req: IdempotentUnaryRequest, ctx: HandlerContext): Promise<MessageInitShape<typeof IdempotentUnaryResponseSchema>>
}

export function ConformanceServiceHandlers(impl: ConformanceServiceServiceImpl): ServiceHandlers {
  const unary: ServiceHandlers['unary'] = {}
  const stream: ServiceHandlers['stream'] = {}
  unary["Unary"] = async (input, ctx) => {
    const req = ctx.kind === 'json' ? fromJson(UnaryRequestSchema, JSON.parse(new TextDecoder().decode(input))) : fromBinary(UnaryRequestSchema, input)
    const v = create(UnaryResponseSchema, await impl.unary(req, ctx))
    return ctx.kind === 'json' ? new TextEncoder().encode(JSON.stringify(toJson(UnaryResponseSchema, v, toJsonOpts))) : toBinary(UnaryResponseSchema, v)
  }
  stream["ServerStream"] = async (input, ctx, emit) => {
    const req = ctx.kind === 'json' ? fromJson(ServerStreamRequestSchema, JSON.parse(new TextDecoder().decode(input))) : fromBinary(ServerStreamRequestSchema, input)
    const enc = (v: MessageInitShape<typeof ServerStreamResponseSchema>) => { const msg = create(ServerStreamResponseSchema, v); return ctx.kind === 'json' ? new TextEncoder().encode(JSON.stringify(toJson(ServerStreamResponseSchema, msg, toJsonOpts))) : toBinary(ServerStreamResponseSchema, msg) }
    for await (const v of await impl.serverStream(req, ctx)) { await emit(enc(v), false) }
    await emit(new Uint8Array(0), true)
  }
  unary["ClientStream"] = async (input, ctx) => {
    const req = ctx.kind === 'json' ? fromJson(ClientStreamRequestSchema, JSON.parse(new TextDecoder().decode(input))) : fromBinary(ClientStreamRequestSchema, input)
    const v = create(ClientStreamResponseSchema, await impl.clientStream(req, ctx))
    return ctx.kind === 'json' ? new TextEncoder().encode(JSON.stringify(toJson(ClientStreamResponseSchema, v, toJsonOpts))) : toBinary(ClientStreamResponseSchema, v)
  }
  stream["BidiStream"] = async (input, ctx, emit) => {
    const req = ctx.kind === 'json' ? fromJson(BidiStreamRequestSchema, JSON.parse(new TextDecoder().decode(input))) : fromBinary(BidiStreamRequestSchema, input)
    const enc = (v: MessageInitShape<typeof BidiStreamResponseSchema>) => { const msg = create(BidiStreamResponseSchema, v); return ctx.kind === 'json' ? new TextEncoder().encode(JSON.stringify(toJson(BidiStreamResponseSchema, msg, toJsonOpts))) : toBinary(BidiStreamResponseSchema, msg) }
    for await (const v of await impl.bidiStream(req, ctx)) { await emit(enc(v), false) }
    await emit(new Uint8Array(0), true)
  }
  unary["Unimplemented"] = async (input, ctx) => {
    const req = ctx.kind === 'json' ? fromJson(UnimplementedRequestSchema, JSON.parse(new TextDecoder().decode(input))) : fromBinary(UnimplementedRequestSchema, input)
    const v = create(UnimplementedResponseSchema, await impl.unimplemented(req, ctx))
    return ctx.kind === 'json' ? new TextEncoder().encode(JSON.stringify(toJson(UnimplementedResponseSchema, v, toJsonOpts))) : toBinary(UnimplementedResponseSchema, v)
  }
  unary["IdempotentUnary"] = async (input, ctx) => {
    const req = ctx.kind === 'json' ? fromJson(IdempotentUnaryRequestSchema, JSON.parse(new TextDecoder().decode(input))) : fromBinary(IdempotentUnaryRequestSchema, input)
    const v = create(IdempotentUnaryResponseSchema, await impl.idempotentUnary(req, ctx))
    return ctx.kind === 'json' ? new TextEncoder().encode(JSON.stringify(toJson(IdempotentUnaryResponseSchema, v, toJsonOpts))) : toBinary(IdempotentUnaryResponseSchema, v)
  }
  return { unary, stream }
}

